build:
	(cd dcindexLib && make)
	(cd litelasticLib && make)
	(cd litestacLib && make)
	(cd notebookLib && make)
	(cd xarrayLib && make)

build-root:
	(cd dcindexLib && make build-root)
	(cd litelasticLib && make build-root)
	(cd litestacLib && make build-root)
	(cd notebookLib && make build-root)
	(cd xarrayLib && make build-root)


